//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_emp
    {
        public int id { get; set; }
        public string emp_name { get; set; }
        public string emp_father { get; set; }
        public string emp_nationality { get; set; }
        public string emp_religion { get; set; }
        public string emp_exp { get; set; }
        public string emp_cnic { get; set; }
        public string emp_qual { get; set; }
        public string emp_sex { get; set; }
        public string emp_marital { get; set; }
        public Nullable<System.DateTime> emp_dob { get; set; }
        public Nullable<System.DateTime> joining_date { get; set; }
        public Nullable<System.DateTime> leaving_date { get; set; }
        public string emp_email { get; set; }
        public string emp_address { get; set; }
        public string emp_remarks { get; set; }
        public Nullable<int> emp_pay { get; set; }
        public string emp_cell { get; set; }
        public string emp_phone { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string created_by { get; set; }
        public Nullable<int> emp_type_id { get; set; }
        public string emp_type { get; set; }
        public string is_active { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int emp_title_id { get; set; }
        public int emp_designation_id { get; set; }
        public byte[] image { get; set; }
        public int branch_id { get; set; }
    }
}
