//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_institute
    {
        public int institute_id { get; set; }
        public byte[] institute_logo { get; set; }
        public string institute_name { get; set; }
        public string institute_cell { get; set; }
        public string institute_phone { get; set; }
        public Nullable<System.DateTime> installation_date { get; set; }
        public string expiry_message { get; set; }
        public Nullable<System.DateTime> expiry_date { get; set; }
        public string expiry_warning_message { get; set; }
        public Nullable<int> expiry_warning_day { get; set; }
        public string expiry_instant { get; set; }
        public string institute_address { get; set; }
        public string institute_quote { get; set; }
        public string institute_owner_name { get; set; }
        public string institute_owner_cell { get; set; }
        public byte[] male_image { get; set; }
        public byte[] female_image { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public string mac { get; set; }
        public string isMultiPartSMSAccess { get; set; }
        public int id { get; set; }
    }
}
