//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fine
    {
        public int id { get; set; }
        public int std_id { get; set; }
        public int session_id { get; set; }
        public int fine_type_id { get; set; }
        public string fine_type { get; set; }
        public string fine_description { get; set; }
        public Nullable<int> amount { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> fine_date { get; set; }
        public string month { get; set; }
        public Nullable<int> monthId { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public int branch_id { get; set; }
    }
}
