//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fee_vouchers
    {
        public int id { get; set; }
        public string rem_tution_fee { get; set; }
        public string rem_security_fee { get; set; }
        public string rem_other_fee { get; set; }
        public string other_exp_type { get; set; }
        public int other_exp_type_id { get; set; }
        public int other_exp_id { get; set; }
        public string rem_transport_fee { get; set; }
        public string rem_exam_fee { get; set; }
        public string rem_fine_fee { get; set; }
        public string std_id { get; set; }
        public string month { get; set; }
        public string reciept_no { get; set; }
        public string rem_adm_fee { get; set; }
        public string rem_reg_fee { get; set; }
        public string total { get; set; }
        public string created_by { get; set; }
        public System.DateTime date_time { get; set; }
        public string isActive { get; set; }
        public int branch_id { get; set; }
    }
}
