//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fees_voucher
    {
        public int id { get; set; }
        public int std_id { get; set; }
        public int fees_generated_id { get; set; }
        public string receipt_no_full { get; set; }
        public int receipt_no { get; set; }
        public int total_amount { get; set; }
        public int total_paid { get; set; }
        public string is_active { get; set; }
        public string created_by { get; set; }
        public System.DateTime date_time { get; set; }
        public int emp_id { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
