//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_exams_data_entry
    {
        public int id { get; set; }
        public int session_id { get; set; }
        public Nullable<int> exam_id { get; set; }
        public Nullable<int> class_id { get; set; }
        public Nullable<int> section_id { get; set; }
        public int std_id { get; set; }
        public string std_name { get; set; }
        public Nullable<int> subject_id { get; set; }
        public string subject_name { get; set; }
        public string subject_total { get; set; }
        public int subject_total_int { get; set; }
        public string subject_obtained { get; set; }
        public Nullable<int> subject_obtained_int { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public string subject_percentage { get; set; }
        public string subject_grade { get; set; }
        public string subject_remarks { get; set; }
        public string total_marks { get; set; }
        public string obtained_marks { get; set; }
        public string percentage { get; set; }
        public string grade { get; set; }
        public string remarks { get; set; }
        public string total_remarks { get; set; }
        public string position { get; set; }
        public int branch_id { get; set; }
    }
}
