//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fee_admin_panel
    {
        public int id { get; set; }
        public string tution_fee { get; set; }
        public string reg_fee { get; set; }
        public string adm_fee { get; set; }
        public string security_fee { get; set; }
        public string exam_fee { get; set; }
        public string other_fee { get; set; }
        public string fine_fee { get; set; }
        public string pay_cash_btn { get; set; }
        public string cancel_challan { get; set; }
        public string waveoff { get; set; }
        public int branch_id { get; set; }
    }
}
