//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_exams
    {
        public int id { get; set; }
        public string exam_name { get; set; }
        public System.DateTime exam_date { get; set; }
        public string exam_abb { get; set; }
        public int exam_type_id { get; set; }
        public int device_type_id { get; set; }
        public int session_id { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int created_emp_id { get; set; }
        public int updated_emp_id { get; set; }
        public System.DateTime created_date_time { get; set; }
        public System.DateTime updated_date_time { get; set; }
        public int branch_id { get; set; }
    }
}
