//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fees_generated
    {
        public int id { get; set; }
        public int std_id { get; set; }
        public int fees_category_id { get; set; }
        public string fees_category { get; set; }
        public int fees_sub_category_id { get; set; }
        public string fees_sub_category { get; set; }
        public int actual_amount { get; set; }
        public int amount { get; set; }
        public int rem_amount { get; set; }
        public int discount { get; set; }
        public int wave_off { get; set; }
        public int month { get; set; }
        public string month_name { get; set; }
        public int class_id { get; set; }
        public string class_name { get; set; }
        public int section_id { get; set; }
        public string section_name { get; set; }
        public int year { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime due_date { get; set; }
        public int session_id { get; set; }
        public string is_active { get; set; }
        public string created_by { get; set; }
        public int emp_id { get; set; }
        public System.DateTime date_time { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
