//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_rfid_assignment
    {
        public int session_id { get; set; }
        public int card_holder_id { get; set; }
        public string card_no { get; set; }
        public string is_std { get; set; }
        public string created_by { get; set; }
        public System.DateTime date_time { get; set; }
        public int emp_id { get; set; }
        public int branch_id { get; set; }
    }
}
