//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_complaint_type
    {
        public int id { get; set; }
        public string complaint_type { get; set; }
        public string complaint_type_abb { get; set; }
        public string remarks { get; set; }
        public int complaint_from_id { get; set; }
        public int branch_id { get; set; }
    }
}
