//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fee_paid
    {
        public int id { get; set; }
        public Nullable<int> std_id { get; set; }
        public string reg_fee_paid { get; set; }
        public string adm_fee_paid { get; set; }
        public string security_fee_paid { get; set; }
        public string exam_fee_paid { get; set; }
        public string transport_fee_paid { get; set; }
        public string tution_fee_paid { get; set; }
        public string other_exp_paid { get; set; }
        public string other_exp_type { get; set; }
        public string other_exp_type_id { get; set; }
        public int other_exp_id { get; set; }
        public string fine_fee_paid { get; set; }
        public string fine_fee_wave_off { get; set; }
        public string tution_fee_wave_off { get; set; }
        public string other_fee_wave_off { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string created_by { get; set; }
        public string month { get; set; }
        public Nullable<int> receipt_no { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public int session_id { get; set; }
        public int fees_collection_place_id { get; set; }
        public string fees_collection_place { get; set; }
        public int branch_id { get; set; }
    }
}
