//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_exam_admin_panel
    {
        public int id { get; set; }
        public string position_visibility { get; set; }
        public string position_text_visibility { get; set; }
        public string position_percentage { get; set; }
        public string position_limit { get; set; }
        public string attendance_visibility { get; set; }
        public string attendance_text_visibility { get; set; }
        public string image_visibility { get; set; }
        public string remarks_visibility { get; set; }
        public string remarks_text_visibility { get; set; }
        public string teacher_visibility { get; set; }
        public string principal_visibility { get; set; }
        public string parents_visibility { get; set; }
        public string teacher_sig_text { get; set; }
        public string principal_sig_text { get; set; }
        public string parents_sig_text { get; set; }
        public byte[] teacher_sig_image { get; set; }
        public byte[] principal_sig_image { get; set; }
        public byte[] parents_sig_image { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
