//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_roll_no
    {
        public int id { get; set; }
        public Nullable<int> class_id { get; set; }
        public string class_name { get; set; }
        public Nullable<int> last_roll_no { get; set; }
        public Nullable<int> last_adm_no { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public Nullable<int> section_id { get; set; }
        public string section_name { get; set; }
        public Nullable<int> prefix_adm_no_id { get; set; }
        public Nullable<int> prefix_roll_no_id { get; set; }
        public int branch_id { get; set; }
    }
}
