//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fee_history_by_amount
    {
        public int id { get; set; }
        public Nullable<int> std_id { get; set; }
        public Nullable<int> receipt_no { get; set; }
        public string std_name { get; set; }
        public string father_name { get; set; }
        public string adm_no { get; set; }
        public string month { get; set; }
        public string class_name { get; set; }
        public string section_name { get; set; }
        public string date { get; set; }
        public Nullable<int> adm_fee { get; set; }
        public Nullable<int> reg_fee { get; set; }
        public Nullable<int> tution_fee { get; set; }
        public Nullable<int> exam_fee { get; set; }
        public Nullable<int> securtiy_fee { get; set; }
        public Nullable<int> other_fee { get; set; }
        public Nullable<int> pending_fee { get; set; }
        public string pending_fee_months { get; set; }
        public Nullable<int> fine_fee { get; set; }
        public string fine_fee_months { get; set; }
        public Nullable<int> total_fee { get; set; }
        public Nullable<int> paid_fee { get; set; }
        public Nullable<int> remaining_fee { get; set; }
        public string amoun_in_words { get; set; }
        public string received_by { get; set; }
        public Nullable<int> session_id { get; set; }
        public int branch_id { get; set; }
    }
}
