//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_complaint_register
    {
        public int id { get; set; }
        public int std_id { get; set; }
        public int session_id { get; set; }
        public int complaint_type_id { get; set; }
        public int complaint_status_id { get; set; }
        public int complaint_from_id { get; set; }
        public string complaint_remarks { get; set; }
        public string complaint_resolved_remarks { get; set; }
        public System.DateTime complaint_date { get; set; }
        public System.DateTime complaint_resolved_date { get; set; }
        public string created_by { get; set; }
        public string updated_by { get; set; }
        public int emp_id { get; set; }
        public System.DateTime created_date_time { get; set; }
        public System.DateTime updated_date_time { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
