//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_prefix_roll_no
    {
        public int id { get; set; }
        public string prefix { get; set; }
        public string prefix_abbreviation { get; set; }
        public Nullable<int> sort_order { get; set; }
        public int branch_id { get; set; }
    }
}
