//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_investments
    {
        public int id { get; set; }
        public int investor_id { get; set; }
        public string investor_name { get; set; }
        public string cheque_no { get; set; }
        public int amount { get; set; }
        public string description { get; set; }
        public System.DateTime investment_date { get; set; }
        public string created_by { get; set; }
        public System.DateTime date_time { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public int branch_id { get; set; }
    }
}
