//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_exam_entry
    {
        public int id { get; set; }
        public Nullable<int> std_id { get; set; }
        public string std_name { get; set; }
        public Nullable<int> class_id { get; set; }
        public string class_name { get; set; }
        public Nullable<int> exam_id { get; set; }
        public string exam_name { get; set; }
        public Nullable<int> section_id { get; set; }
        public string section_name { get; set; }
        public string subj1_marks { get; set; }
        public string subj2_marks { get; set; }
        public string subj3_marks { get; set; }
        public string subj4_marks { get; set; }
        public string subj5_marks { get; set; }
        public string subj6_marks { get; set; }
        public string subj7_marks { get; set; }
        public string subj8_marks { get; set; }
        public string subj9_marks { get; set; }
        public string subj10_marks { get; set; }
        public string subj1_total { get; set; }
        public string subj2_total { get; set; }
        public string subj3_total { get; set; }
        public string subj4_total { get; set; }
        public string subj5_total { get; set; }
        public string subj6_total { get; set; }
        public string subj7_total { get; set; }
        public string subj8_total { get; set; }
        public string subj9_total { get; set; }
        public string subj10_total { get; set; }
        public string subj_id { get; set; }
        public string subj_total { get; set; }
        public string subj_name { get; set; }
        public string subj_marks { get; set; }
        public string subj1_id { get; set; }
        public string subj2_id { get; set; }
        public string subj3_id { get; set; }
        public string subj1_name { get; set; }
        public string subj2_name { get; set; }
        public string subj3_name { get; set; }
        public string subj4_id { get; set; }
        public string subj5_id { get; set; }
        public string subj6_id { get; set; }
        public string subj7_id { get; set; }
        public string subj8_id { get; set; }
        public string subj9_id { get; set; }
        public string subj10_id { get; set; }
        public string subj4_name { get; set; }
        public string subj5_name { get; set; }
        public string subj6_name { get; set; }
        public string subj7_name { get; set; }
        public string subj8_name { get; set; }
        public string subj9_name { get; set; }
        public string subj10_name { get; set; }
        public string obtained_marks { get; set; }
        public string total_marks { get; set; }
        public string percentage { get; set; }
        public string remarks { get; set; }
        public string position { get; set; }
        public int branch_id { get; set; }
    }
}
