//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_voucher_entries
    {
        public int id { get; set; }
        public Nullable<int> voucher_id { get; set; }
        public string voucher_no { get; set; }
        public Nullable<int> voucher_no_int { get; set; }
        public Nullable<int> voucher_type_id { get; set; }
        public string voucher_type { get; set; }
        public Nullable<int> account_head_id { get; set; }
        public string account_head { get; set; }
        public Nullable<int> account_detail_id { get; set; }
        public string account_detail { get; set; }
        public string description { get; set; }
        public Nullable<double> debit { get; set; }
        public Nullable<double> credit { get; set; }
        public Nullable<double> balance { get; set; }
        public Nullable<double> last_voucher_no { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
