//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_exams_date_sheet
    {
        public int id { get; set; }
        public int exam_id { get; set; }
        public int subject_id { get; set; }
        public int section_id { get; set; }
        public int class_id { get; set; }
        public Nullable<System.DateTime> exam_date { get; set; }
        public string exam_time { get; set; }
        public string remarks { get; set; }
        public Nullable<System.DateTime> created_date_time { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<int> created_emp_id { get; set; }
        public Nullable<int> updated_emp_id { get; set; }
        public Nullable<sbyte> is_active { get; set; }
        public Nullable<sbyte> is_deleted { get; set; }
        public Nullable<sbyte> is_synchronized { get; set; }
        public Nullable<int> sort_order { get; set; }
        public int branch_id { get; set; }
    }
}
