//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_account_entry
    {
        public int id { get; set; }
        public int branch_id { get; set; }
        public int account_id { get; set; }
        public string created_by { get; set; }
        public string amount { get; set; }
        public string expenditure { get; set; }
        public System.DateTime date_time { get; set; }
        public string cheque_no { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public System.DateTime date { get; set; }
        public string account_name { get; set; }
    }
}
