//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_voucher_types
    {
        public int id { get; set; }
        public string voucher_type { get; set; }
        public string description { get; set; }
        public int last_voucher_no { get; set; }
        public string last_voucher { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
