//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_accounts
    {
        public int id { get; set; }
        public int branch_id { get; set; }
        public string account_name { get; set; }
        public string account_desc { get; set; }
        public string account_holder_name { get; set; }
        public string account_holder_cell { get; set; }
        public string account_holder_phn { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string created_by { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
    }
}
