//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_emp_attendence
    {
        public int id { get; set; }
        public int session_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string attendence { get; set; }
        public Nullable<System.DateTime> attendence_date { get; set; }
        public string emp_type { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string emp_name { get; set; }
        public string created_by { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public string att_percentage { get; set; }
        public string total_days { get; set; }
        public string total_abs { get; set; }
        public string total_presents { get; set; }
        public string total_leaves { get; set; }
        public int branch_id { get; set; }
    }
}
