//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_sms_queue
    {
        public int id { get; set; }
        public int receiver_id { get; set; }
        public int receiver_type_id { get; set; }
        public string receiver_cell_no { get; set; }
        public string receiver_name { get; set; }
        public string sms_message { get; set; }
        public int sms_length { get; set; }
        public string sms_type { get; set; }
        public int sms_type_id { get; set; }
        public System.DateTime date_time { get; set; }
        public int sort_order { get; set; }
        public string created_by { get; set; }
        public int emp_id { get; set; }
        public string is_sent { get; set; }
        public string is_periority { get; set; }
        public string sender_cell_no { get; set; }
        public string sender_com_port { get; set; }
        public Nullable<int> institute_id { get; set; }
        public string institute_name { get; set; }
        public string institute_cell { get; set; }
        public Nullable<System.DateTime> created_date_time { get; set; }
        public Nullable<System.DateTime> downloaded_date_time { get; set; }
        public Nullable<System.DateTime> updated_date_time { get; set; }
        public Nullable<sbyte> isSynchronized { get; set; }
        public Nullable<sbyte> isEncoded { get; set; }
        public int branch_id { get; set; }
    }
}
