//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fees_voucher_history
    {
        public int id { get; set; }
        public int std_id { get; set; }
        public string std_name { get; set; }
        public string father_name { get; set; }
        public string adm_no { get; set; }
        public string fees_category { get; set; }
        public int amount { get; set; }
        public string amount_in_words { get; set; }
        public int total_amount { get; set; }
        public int total_paid { get; set; }
        public int total_remaining { get; set; }
        public int discount { get; set; }
        public int wave_off { get; set; }
        public string month_name { get; set; }
        public System.DateTime date { get; set; }
        public System.DateTime due_date { get; set; }
        public int receipt_no { get; set; }
        public string receipt_no_full { get; set; }
        public string class_name { get; set; }
        public string section_name { get; set; }
        public int emp_id { get; set; }
        public string fees_collection_place { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
