//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_subjects
    {
        public int id { get; set; }
        public Nullable<int> class_id { get; set; }
        public string class_name { get; set; }
        public Nullable<int> emp_id { get; set; }
        public string emp_name { get; set; }
        public string section_name { get; set; }
        public string is_active { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string created_by { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public string roll_no_format { get; set; }
        public int branch_id { get; set; }
    }
}
