//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_branches
    {
        public int branch_id { get; set; }
        public int institute_id { get; set; }
        public string branch_name { get; set; }
        public string branch_address { get; set; }
        public string branch_city { get; set; }
        public string branch_phone { get; set; }
        public string branch_cell { get; set; }
        public string branch_owner_name { get; set; }
        public string branch_owner_cell { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
    }
}
