//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fees_actual
    {
        public int id { get; set; }
        public int std_id { get; set; }
        public int fees_category_id { get; set; }
        public string fees_category { get; set; }
        public Nullable<int> fees_sub_category_id { get; set; }
        public string fees_sub_category { get; set; }
        public int actual_amount { get; set; }
        public int discount { get; set; }
        public int amount { get; set; }
        public int emp_id { get; set; }
        public System.DateTime date_time { get; set; }
        public string created_by { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
