//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_chart_of_accounts
    {
        public int id { get; set; }
        public int branch_id { get; set; }
        public string account_name { get; set; }
        public int p_id { get; set; }
        public string account_full_code { get; set; }
        public int account_code { get; set; }
        public int account_type_id { get; set; }
        public int account_category_id { get; set; }
        public string isCashAccount { get; set; }
        public System.DateTime date_time { get; set; }
        public string created_by { get; set; }
        public int emp_id { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
    }
}
