//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_exam_requirements
    {
        public int id { get; set; }
        public Nullable<double> lower_percentage { get; set; }
        public Nullable<double> upper_percentage { get; set; }
        public string remarks { get; set; }
        public string overall_remarks { get; set; }
        public string grade { get; set; }
        public Nullable<int> fail_subjects { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
