//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_other_fee
    {
        public int id { get; set; }
        public int std_id { get; set; }
        public int session_id { get; set; }
        public int fee_type_id { get; set; }
        public string fee_type { get; set; }
        public string description { get; set; }
        public int amount { get; set; }
        public System.DateTime date { get; set; }
        public int month_id { get; set; }
        public string month_name { get; set; }
        public System.DateTime date_time { get; set; }
        public string created_by { get; set; }
        public int branch_id { get; set; }
    }
}
