//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_emp_thumb_enroll
    {
        public int id { get; set; }
        public int emp_id { get; set; }
        public string template { get; set; }
        public byte[] image1 { get; set; }
        public byte[] image2 { get; set; }
        public byte[] image3 { get; set; }
        public int quality2 { get; set; }
        public System.DateTime date_time { get; set; }
        public int quality1 { get; set; }
        public int quality3 { get; set; }
        public string hand { get; set; }
        public int finger_type_id { get; set; }
        public string is_active { get; set; }
        public string created_by { get; set; }
        public int emp_login_id { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
