//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_classes
    {
        public int id { get; set; }
        public string reg_fee { get; set; }
        public string adm_fee { get; set; }
        public string security_fee { get; set; }
        public string tution_fee { get; set; }
        public string transport_charges { get; set; }
        public string boarding_fee { get; set; }
        public string misc_charges { get; set; }
        public string exam_fee { get; set; }
        public string stationary_charges { get; set; }
        public string books_charges { get; set; }
        public string other_exp { get; set; }
        public string roll_no_format { get; set; }
        public string is_active { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string created_by { get; set; }
        public string class_name { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
