//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fee
    {
        public int id { get; set; }
        public string reg_fee { get; set; }
        public int session_id { get; set; }
        public string adm_fee { get; set; }
        public string tution_fee { get; set; }
        public string exam_fee { get; set; }
        public string fine_fee { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string created_by { get; set; }
        public string transport_fee { get; set; }
        public string security_fee { get; set; }
        public string other_exp { get; set; }
        public string rem_adm_fee { get; set; }
        public string rem_reg_fee { get; set; }
        public string rem_tution_fee { get; set; }
        public string rem_exam_fee { get; set; }
        public string rem_transport_fee { get; set; }
        public string rem_security_fee { get; set; }
        public string rem_other_exp { get; set; }
        public string rem_fine_fee { get; set; }
        public string month { get; set; }
        public Nullable<int> std_id { get; set; }
        public Nullable<int> last_receipt_no { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string isActive { get; set; }
        public int branch_id { get; set; }
    }
}
