//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_bank_details
    {
        public string bank_name { get; set; }
        public int id { get; set; }
        public int branch_id { get; set; }
        public byte[] bank_logo { get; set; }
        public string branch_name { get; set; }
        public string account_no { get; set; }
        public string account_title { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
    }
}
