//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_voucher
    {
        public int id { get; set; }
        public string voucher_no { get; set; }
        public int voucher_no_int { get; set; }
        public int voucher_type_id { get; set; }
        public string voucher_type { get; set; }
        public System.DateTime voucher_date { get; set; }
        public string voucher_description { get; set; }
        public double amount { get; set; }
        public Nullable<System.DateTime> cheque_date { get; set; }
        public Nullable<int> cheque_no { get; set; }
        public string is_posted { get; set; }
        public string created_by { get; set; }
        public System.DateTime date_time { get; set; }
        public int emp_id { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
