//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_exams_subject_assignment
    {
        public int subject_id { get; set; }
        public int section_id { get; set; }
        public Nullable<int> emp_id { get; set; }
        public Nullable<int> std_id { get; set; }
        public Nullable<int> created_emp_id { get; set; }
        public Nullable<int> updated_emp_id { get; set; }
        public System.DateTime created_date_time { get; set; }
        public System.DateTime updated_date_time { get; set; }
        public string is_active { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public Nullable<int> sort_order { get; set; }
        public int branch_id { get; set; }
    }
}
