//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_exams_subjects_group
    {
        public int id { get; set; }
        public string group_name { get; set; }
        public string group_name_abb { get; set; }
        public int sort_order { get; set; }
        public string is_active { get; set; }
        public int branch_id { get; set; }
    }
}
