//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sms_fees_paid
    {
        public int id { get; set; }
        public int std_id { get; set; }
        public int fees_generated_id { get; set; }
        public int fees_category_id { get; set; }
        public string fees_category { get; set; }
        public Nullable<int> fees_sub_category_id { get; set; }
        public string fees_sub_category { get; set; }
        public int amount { get; set; }
        public int amount_paid { get; set; }
        public string amount_in_words { get; set; }
        public int total_amount { get; set; }
        public int total_paid { get; set; }
        public int total_remaining { get; set; }
        public int discount { get; set; }
        public int wave_off { get; set; }
        public int month { get; set; }
        public string month_name { get; set; }
        public int year { get; set; }
        public System.DateTime date { get; set; }
        public int receipt_no { get; set; }
        public string receipt_no_full { get; set; }
        public int class_id { get; set; }
        public string class_name { get; set; }
        public int section_id { get; set; }
        public string section_name { get; set; }
        public int session_id { get; set; }
        public int emp_id { get; set; }
        public string created_by { get; set; }
        public System.DateTime date_time { get; set; }
        public Nullable<int> fees_collection_place_id { get; set; }
        public string fees_collection_place { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
        public string deletion { get; set; }
        public int branch_id { get; set; }
    }
}
