//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class smsEntitiesConnectionString : DbContext
    {
        public smsEntitiesConnectionString()
            : base("name=smsEntitiesConnectionString")
        {
        }
        public void FixEfProviderServicesProblem()
        {
            //The Entity Framework provider type 'System.Data.Entity.SqlServer.SqlProviderServices, EntityFramework.SqlServer'
            //for the 'System.Data.SqlClient' ADO.NET provider could not be loaded. 
            //Make sure the provider assembly is available to the running application. 
            //See http://go.microsoft.com/fwlink/?LinkId=260882 for more information.

            var instance = System.Data.Entity.SqlServer.SqlProviderServices.Instance;
        }
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }

        #region Pre requisite
        public virtual DbSet<sms_years> sms_years { get; set; }
        public virtual DbSet<sms_months> sms_months { get; set; }
        public virtual DbSet<sms_prefix_admission_no> sms_prefix_admission_no { get; set; }
        public virtual DbSet<sms_prefix_roll_no> sms_prefix_roll_no { get; set; }       
        public virtual DbSet<sms_sessions> sms_sessions { get; set; }
        public virtual DbSet<sms_settings> sms_settings { get; set; }
        public virtual DbSet<sms_institute> sms_institute { get; set; }
        public virtual DbSet<sms_branches> sms_branches { get; set; }
        public virtual DbSet<sms_classes> sms_classes { get; set; }
        public virtual DbSet<sms_subjects> sms_subjects { get; set; }
        #endregion

        #region student
        public virtual DbSet<sms_admission> sms_admission { get; set; }
        public virtual DbSet<sms_student_attendence> sms_student_attendence { get; set; }
        #endregion

        #region Accounts
        public virtual DbSet<sms_voucher_types> sms_voucher_types { get; set; }
        public virtual DbSet<sms_account_types> sms_account_types { get; set; }       
        public virtual DbSet<sms_accounts_category> sms_accounts_category { get; set; }
        public virtual DbSet<sms_chart_of_accounts> sms_chart_of_accounts { get; set; }
        public virtual DbSet<sms_voucher> sms_voucher { get; set; }
        public virtual DbSet<sms_voucher_cancel> sms_voucher_cancel { get; set; }
        public virtual DbSet<sms_voucher_entries> sms_voucher_entries { get; set; }        
        #endregion       

        #region complaints
        public virtual DbSet<sms_complaint_status> sms_complaint_status { get; set; }
        public virtual DbSet<sms_complaint_type> sms_complaint_type { get; set; }
        public virtual DbSet<sms_complaint_from> sms_complaint_from { get; set; }
        public virtual DbSet<sms_complaint_register> sms_complaint_register { get; set; }
        #endregion

        #region employees
        public virtual DbSet<sms_emp_title> sms_emp_title { get; set; }
        public virtual DbSet<sms_emp_types> sms_emp_types { get; set; }
        public virtual DbSet<sms_emp_designation> sms_emp_designation { get; set; }
        public virtual DbSet<sms_emp> sms_emp { get; set; }
        public virtual DbSet<sms_emp_attendance> sms_emp_attendance { get; set; }
        public virtual DbSet<sms_emp_attendence> sms_emp_attendence { get; set; }        
        public virtual DbSet<sms_emp_image> sms_emp_image { get; set; }
        public virtual DbSet<sms_emp_login> sms_emp_login { get; set; }
        public virtual DbSet<sms_emp_thumb_enroll> sms_emp_thumb_enroll { get; set; }       
        public virtual DbSet<sms_roles> sms_roles { get; set; }
        public virtual DbSet<sms_roles_assignment> sms_roles_assignment { get; set; }
        #endregion

        #region exams
        public virtual DbSet<sms_exam_admin_panel> sms_exam_admin_panel { get; set; }
        public virtual DbSet<sms_exam_requirements> sms_exam_requirements { get; set; }
        public virtual DbSet<sms_exams_subject_type> sms_exams_subject_type { get; set; }
        public virtual DbSet<sms_exams_subjects_group> sms_exams_subjects_group { get; set; }
        public virtual DbSet<sms_exams_subjects> sms_exams_subjects { get; set; }
        public virtual DbSet<sms_exams_subject_assignment> sms_exams_subject_assignment { get; set; }
        public virtual DbSet<sms_exams_types> sms_exams_types { get; set; }
        public virtual DbSet<sms_exams> sms_exams { get; set; }
        public virtual DbSet<sms_exams_data_entry> sms_exams_data_entry { get; set; }
        public virtual DbSet<sms_exams_date_sheet> sms_exams_date_sheet { get; set; }
        #endregion

        #region Fees
        public virtual DbSet<sms_finance_type> sms_finance_type { get; set; }
        public virtual DbSet<sms_fees_category> sms_fees_category { get; set; }
        public virtual DbSet<sms_fee_admin_panel> sms_fee_admin_panel { get; set; }
        public virtual DbSet<sms_fees_admin_panel> sms_fees_admin_panel { get; set; }
        public virtual DbSet<sms_fee_note> sms_fee_note { get; set; }
        public virtual DbSet<sms_fees_collection_place> sms_fees_collection_place { get; set; }
        public virtual DbSet<sms_fees_note> sms_fees_note { get; set; }
        public virtual DbSet<sms_fees_package> sms_fees_package { get; set; }
        public virtual DbSet<sms_fees_sub_category> sms_fees_sub_category { get; set; }
        public virtual DbSet<sms_fees_types> sms_fees_types { get; set; }
        public virtual DbSet<sms_fees_classes> sms_fees_classes { get; set; }
        public virtual DbSet<sms_fees_actual> sms_fees_actual { get; set; }
        public virtual DbSet<sms_fees_generated> sms_fees_generated { get; set; }
        public virtual DbSet<sms_fees_paid> sms_fees_paid { get; set; }
        public virtual DbSet<sms_fees_voucher> sms_fees_voucher { get; set; }
        public virtual DbSet<sms_fees_voucher_history> sms_fees_voucher_history { get; set; }
        #endregion

        public virtual DbSet<sms_bank_details> sms_bank_details { get; set; }
        public virtual DbSet<sms_city_area> sms_city_area { get; set; }
        public virtual DbSet<sms_device_info> sms_device_info { get; set; }
        public virtual DbSet<sms_finger_types> sms_finger_types { get; set; }
        public virtual DbSet<sms_freind_type> sms_freind_type { get; set; }
        public virtual DbSet<sms_friend_list> sms_friend_list { get; set; }        
        public virtual DbSet<sms_history> sms_history { get; set; }        
        public virtual DbSet<sms_last_receipt_no> sms_last_receipt_no { get; set; }       
        public virtual DbSet<sms_rfid_assignment> sms_rfid_assignment { get; set; }       
        public virtual DbSet<sms_roll_no> sms_roll_no { get; set; }
        public virtual DbSet<sms_saved> sms_saved { get; set; }                
        public virtual DbSet<sms_sms_queue> sms_sms_queue { get; set; }
        public virtual DbSet<sms_sms_receiver_type> sms_sms_receiver_type { get; set; }
        public virtual DbSet<sms_sms_type> sms_sms_type { get; set; }
        
    }
}
