//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_events_images
    {
        public int id { get; set; }
        public byte[] image { get; set; }
        public int image_id { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
    }
}
