//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_events
    {
        public int id { get; set; }
        public string event_name { get; set; }
        public string event_description { get; set; }
        public Nullable<System.DateTime> event_date { get; set; }
        public string created_by { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string insertion { get; set; }
        public string updation { get; set; }
    }
}
