//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_datesheet
    {
        public int id { get; set; }
        public string day50 { get; set; }
        public string day51 { get; set; }
        public string day52 { get; set; }
        public string day53 { get; set; }
        public string day54 { get; set; }
        public string day55 { get; set; }
        public string day56 { get; set; }
        public string day57 { get; set; }
        public string day58 { get; set; }
        public string day59 { get; set; }
        public string day60 { get; set; }
        public string day61 { get; set; }
        public string day62 { get; set; }
        public string day63 { get; set; }
        public string day64 { get; set; }
        public string day65 { get; set; }
        public string day66 { get; set; }
        public string day67 { get; set; }
        public string day68 { get; set; }
        public string day69 { get; set; }
        public string day70 { get; set; }
        public string day71 { get; set; }
        public string day72 { get; set; }
        public string day73 { get; set; }
        public string day74 { get; set; }
        public string day75 { get; set; }
        public string day76 { get; set; }
        public string day77 { get; set; }
        public string day78 { get; set; }
        public string day79 { get; set; }
        public string day80 { get; set; }
        public string date1 { get; set; }
        public string date2 { get; set; }
        public string date3 { get; set; }
        public string date4 { get; set; }
        public string date5 { get; set; }
        public string date6 { get; set; }
        public string date7 { get; set; }
        public string date8 { get; set; }
        public string class1 { get; set; }
        public string class2 { get; set; }
        public string class3 { get; set; }
        public string class4 { get; set; }
        public string class5 { get; set; }
        public string class6 { get; set; }
        public string class7 { get; set; }
        public string class8 { get; set; }
        public string class9 { get; set; }
        public string class10 { get; set; }
        public string day1 { get; set; }
        public string day2 { get; set; }
        public string day3 { get; set; }
        public string day4 { get; set; }
        public string day5 { get; set; }
        public string day6 { get; set; }
        public string day7 { get; set; }
        public string day8 { get; set; }
        public string day9 { get; set; }
        public string day10 { get; set; }
        public string day11 { get; set; }
        public string day12 { get; set; }
        public string day13 { get; set; }
        public string day14 { get; set; }
        public string day15 { get; set; }
        public string day16 { get; set; }
        public string day17 { get; set; }
        public string day18 { get; set; }
        public string day19 { get; set; }
        public string day20 { get; set; }
        public string day21 { get; set; }
        public string day22 { get; set; }
        public string day23 { get; set; }
        public string day24 { get; set; }
        public string day25 { get; set; }
        public string day26 { get; set; }
        public string day27 { get; set; }
        public string day28 { get; set; }
        public string day29 { get; set; }
        public string day30 { get; set; }
        public string day31 { get; set; }
        public string day32 { get; set; }
        public string day33 { get; set; }
        public string day34 { get; set; }
        public string day35 { get; set; }
        public string day36 { get; set; }
        public string day37 { get; set; }
        public string day38 { get; set; }
        public string day39 { get; set; }
        public string day40 { get; set; }
        public string day41 { get; set; }
        public string day42 { get; set; }
        public string day43 { get; set; }
        public string day44 { get; set; }
        public string day45 { get; set; }
        public string day46 { get; set; }
        public string day47 { get; set; }
        public string day48 { get; set; }
        public string day49 { get; set; }
        public string date_time { get; set; }
    }
}
