//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_latest_news
    {
        public int id { get; set; }
        public Nullable<System.DateTime> news_date { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
        public string news_heading { get; set; }
        public string news_description { get; set; }
    }
}
