//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SMS.Models.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class web_online_admission
    {
        public int id { get; set; }
        public string name { get; set; }
        public string email { get; set; }
        public string cell_no { get; set; }
        public string pre_school { get; set; }
        public string adress { get; set; }
        public string gender { get; set; }
        public string @class { get; set; }
        public Nullable<System.DateTime> date_time { get; set; }
    }
}
